export default {
  // shoes action types
  GET_SHOES_BY_CATEGORY: 'GET_SHOES_BY_CATEGORY',
  SET_SHOES_BY_CATEGORY: 'SET_SHOES_BY_CATEGORY',
  CL_SHOES_BY_CATEGORY: 'CL_SHOES_BY_CATEGORY',
  CL_ALL_SHOES_BY_CATEGORY: 'CL_ALL_SHOES_BY_CATEGORY',
  FILTER_SHOES: 'FILTER_SHOES',
  // app action types
  SET_SHOES_PARAMETERS: 'SET_SHOES_PARAMETERS',
  CL_SHOES_PARAMETERS: 'CL_SHOES_PARAMETERS',
  SET_SHOES_RESULT: 'SET_SHOES_RESULT',
  CL_SHOES_RESULT: 'CL_SHOES_RESULT',
  SET_RESULT_ATTR: 'SET_RESULT_ATTR',
  SET_RESULT_ATTR_BY_CATEGORY: 'SET_RESULT_ATTR_BY_CATEGORY',
  // category action types
  GET_CATEGORIES_BY_PARENT: 'GET_CATEGORIES_BY_PARENT',
  SET_CATEGORIES: 'SET_CATEGORIES',
};
