export default {
  FILTER_SHOES: 'FILTER_SHOES',
  SET_SHOES_LIST: 'SET_SHOES',
  CL_SHOES_LIST: 'CL_SHOES_LIST',
  SET_SHOES_PARAMETERS: 'SET_SHOES_PARAMETERS',
  CL_SHOES_PARAMETERS: 'CL_SHOES_PARAMETERS',
  GET_CATEGORIES_BY_PARENT: 'GET_CATEGORIES_BY_PARENT',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_RESULT_ATTR: 'SET_RESULT_ATTR',
};
